SuperHeroCreate/Models/ErrorViewModel.cs
using System;

namespace SuperHeroCreate.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperHeroCreate/Models/SuperHero.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;


namespace SuperHeroCreate.Models
{
    public class SuperHero
    {
        [Key]
        public int Id { get; set; }
        public string Name { get; set; }
        public string AlterEgoName { get; set; }
        public string PrimaryAbility { get; set; }
        public string SecondaryAbility { get; set; }
        public string CatchPhrase { get; set; }
    }
}

SuperHeroCreate/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperHeroCreate.Models;

namespace SuperHeroCreate.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperHeroCreate/Controllers/SuperHeroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SuperHeroCreate.Data;
using SuperHeroCreate.Models;

namespace SuperHero_Project.Controllers
{
    public class SuperHeroController : Controller
    {
        private ApplicationDbContext _context;
        public SuperHeroController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: SuperHero
        public ActionResult Index()
        {
            var superHeroes = _context.SuperHeroes.ToList();
            return View(superHeroes);
        }

        // GET: SuperHero/Details/5
        public ActionResult Details(int id)
        {
            var superHero = _context.SuperHeroes.Where(s => s.Id == id).SingleOrDefault();
            return View(superHero);
        }

        // GET: SuperHero/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SuperHero/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SuperHero superHero)
        {
            try
            {
                // TODO: Add insert logic here
                _context.SuperHeroes.Add(superHero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperHero/Edit/5
        public ActionResult Edit(int id)
        {
            var superHero = _context.SuperHeroes.Where(s => s.Id == id).SingleOrDefault();

            return View(superHero);
        }

        // POST: SuperHero/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SuperHero superHero)
        {
            try
            {
                // TODO: Add update logic here

                var superheroedit = _context.SuperHeroes.Where(s => s.Id == superHero.Id).SingleOrDefault();
                superheroedit.Name = superHero.Name;
                superheroedit.AlterEgoName = superHero.AlterEgoName;
                superheroedit.PrimaryAbility = superHero.PrimaryAbility;
                superheroedit.SecondaryAbility = superHero.SecondaryAbility;
                superheroedit.CatchPhrase = superHero.CatchPhrase;
                _context.SaveChanges();


                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperHero/Delete/5
        public ActionResult Delete(int id)
        {
            var superHero = _context.SuperHeroes.Where(s => s.Id == id).SingleOrDefault();
            return View(superHero);
        }

        // POST: SuperHero/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(SuperHero superHero)
        {
            try
            {
                // TODO: Add delete logic here
                _context.SuperHeroes.Remove(superHero);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperHeroCreate/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
   
        <div class="text-center">
            <h1 class="display-4">Welcome To SuperCreate </h1><br>
            <h3>The one stop shop to make the Super Hero of your dreams</h3>
            <img src="https://vignette.wikia.nocookie.net/superman/images/b/b1/Superman_Action_976_Gary_Frank.png">
            

        </div>

SuperHeroCreate/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperHeroCreate</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <BGSOUND src="https://archive.org/download/TheSupermanThemeJohnWilliamsExtendedVersion/The%20Superman%20Theme%20-%20John%20Williams%20%28Extended%20Version%29.ogg" loop=infinite>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperHeroCreate</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SuperHero" asp-action="Create">Create</a>
                            </li>
                            
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2020 - SuperHeroCreate - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @RenderSection("Scripts", required: false)
</body>
</html>

SuperHeroCreate/Views/SuperHero/Create.cshtml
@model SuperHeroCreate.Models.SuperHero

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SuperHero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgoName" class="control-label"></label>
                <input asp-for="AlterEgoName" class="form-control" />
                <span asp-validation-for="AlterEgoName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperHeroCreate/Views/SuperHero/Delete.cshtml
@model SuperHeroCreate.Models.SuperHero

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SuperHero</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgoName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AlterEgoName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperHeroCreate/Views/SuperHero/Details.cshtml
@model SuperHeroCreate.Models.SuperHero

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SuperHero</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.AlterEgoName):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.AlterEgoName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrimaryAbility):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrimaryAbility)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecondaryAbility):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SecondaryAbility)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CatchPhrase):
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CatchPhrase)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

SuperHeroCreate/Views/SuperHero/Edit.cshtml
@model SuperHeroCreate.Models.SuperHero

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SuperHero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AlterEgoName" class="control-label"></label>
                <input asp-for="AlterEgoName" class="form-control" />
                <span asp-validation-for="AlterEgoName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrimaryAbility" class="control-label"></label>
                <input asp-for="PrimaryAbility" class="form-control" />
                <span asp-validation-for="PrimaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecondaryAbility" class="control-label"></label>
                <input asp-for="SecondaryAbility" class="form-control" />
                <span asp-validation-for="SecondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CatchPhrase" class="control-label"></label>
                <input asp-for="CatchPhrase" class="form-control" />
                <span asp-validation-for="CatchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperHeroCreate/Views/SuperHero/Index.cshtml
@model IEnumerable<SuperHeroCreate.Models.SuperHero>

@{
    ViewData["Title"] = "Super Heroes";
}

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlterEgoName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrimaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CatchPhrase)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.AlterEgoName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrimaryAbility)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SecondaryAbility)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CatchPhrase)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

SuperHeroCreate/Views/SuperHero/List.cshtml
@model IEnumerable<SuperHeroCreate.Models.SuperHero>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AlterEgoName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrimaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SecondaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CatchPhrase)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AlterEgoName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PrimaryAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecondaryAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CatchPhrase)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>